apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: flaskapp-middleware
  namespace: flaskapp
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaskapp-ingress
  namespace: flaskapp
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.middlewares: flaskapp-flaskapp-middleware@kubernetescrd
spec:
  rules:
    - host: items.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flaskapp-service
                port:
                  number: 5000

