apiVersion: v1
kind: Secret
metadata:
  name: flaskapp-secret
  namespace: flaskapp
type: Opaque
data:
  app-root-username: YXBwdXNlcg==  # "appuser" (base64 encoded)
  app-root-password: YXBwcGFzc3dvcmQ=  # "apppassword" (base64 encoded)
